name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Java LTS Build and Verify
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B verify

    - name: Simple benchmark test
      run: |
        java --add-opens java.base/java.lang=ALL-UNNAMED \
             --add-opens java.base/java.lang.reflect=ALL-UNNAMED \
             --add-opens java.base/java.nio=ALL-UNNAMED \
             --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
             --add-exports java.base/sun.nio.ch=ALL-UNNAMED \
             --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
             --enable-native-access=ALL-UNNAMED \
             -jar target/benchmarks.jar -foe true -wi 0 -i 1 -f 1 -p num=512 -r 3s
